# Generated by Django 4.2.9 on 2026-03-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('loom_number', models.CharField(max_length=20)),
                ('design', models.CharField(max_length=100)),
                ('meter_woven', models.DecimalField(decimal_places=2, max_digits=8)),
                ('defects', models.IntegerField(default=0)),
                ('work_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('quality', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('defective', 'Defective')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='employee.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
