apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: weaver_db
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
